// ============================================================
// BASE DE DONNÉES DES KANJI — extraite des leçons 1 à 7
// Format: { kanji, on: [], kun: [], meaning, lecon }
// ============================================================

const KANJI_DATA = [

  // ──────────── LEÇON 1 ────────────
  { kanji:"一", on:["イチ","イツ"], kun:["ひと"], meaning:"un, premier", lecon:1 },
  { kanji:"二", on:["ニ"], kun:["ふた"], meaning:"deux", lecon:1 },
  { kanji:"三", on:["サン"], kun:["みつ"], meaning:"trois", lecon:1 },
  { kanji:"四", on:["シ"], kun:["よん","よ","よつ"], meaning:"quatre", lecon:1 },
  { kanji:"五", on:["ゴ"], kun:["いつ"], meaning:"cinq", lecon:1 },
  { kanji:"六", on:["ロク","ロツ"], kun:["むつ"], meaning:"six", lecon:1 },
  { kanji:"七", on:["シチ"], kun:["なな"], meaning:"sept", lecon:1 },
  { kanji:"八", on:["ハチ","ハツ"], kun:["やつ","や"], meaning:"huit", lecon:1 },
  { kanji:"九", on:["キュウ","ク"], kun:["ここの"], meaning:"neuf", lecon:1 },
  { kanji:"十", on:["ジュウ","ジュツ"], kun:["とお"], meaning:"dix", lecon:1 },
  { kanji:"百", on:["ヒャク","ビャク","ピャク"], kun:[], meaning:"cent", lecon:1 },
  { kanji:"千", on:["セン","ゼン"], kun:[], meaning:"mille", lecon:1 },
  { kanji:"万", on:["マン"], kun:[], meaning:"dix mille", lecon:1 },
  { kanji:"円", on:["エン"], kun:[], meaning:"yen, cercle", lecon:1 },
  { kanji:"口", on:["コウ"], kun:["くち","ぐち"], meaning:"bouche", lecon:1 },
  { kanji:"目", on:["モク"], kun:["め"], meaning:"œil", lecon:1 },
  { kanji:"寺", on:["ジ"], kun:["てら"], meaning:"temple bouddhiste", lecon:1 },
  { kanji:"時", on:["ジ"], kun:["とき"], meaning:"heure, moment", lecon:1 },
  { kanji:"山", on:["サン"], kun:["やま"], meaning:"montagne", lecon:1 },

  // ──────────── LEÇON 2 ────────────
  { kanji:"日", on:["ニチ","ニッ","ジツ"], kun:["ひ","び","か"], meaning:"soleil, jour", lecon:2 },
  { kanji:"月", on:["ガツ","ゲツ"], kun:["つき"], meaning:"lune, mois", lecon:2 },
  { kanji:"火", on:["カ"], kun:["ひ","び"], meaning:"feu, mardi", lecon:2 },
  { kanji:"水", on:["スイ"], kun:["みず"], meaning:"eau, mercredi", lecon:2 },
  { kanji:"木", on:["ボク","モク"], kun:["き","こ"], meaning:"arbre, jeudi", lecon:2 },
  { kanji:"金", on:["キン","コン","ゴン"], kun:["かね","かな","がね"], meaning:"or, argent, vendredi", lecon:2 },
  { kanji:"土", on:["ド"], kun:["つち"], meaning:"terre, samedi", lecon:2 },
  { kanji:"曜", on:["ヨウ"], kun:[], meaning:"jour de la semaine", lecon:2 },
  { kanji:"本", on:["ホン"], kun:["もと"], meaning:"livre, origine, compteur (cylindrique)", lecon:2 },
  { kanji:"人", on:["ニン","ジン"], kun:["ひと","り"], meaning:"personne", lecon:2 },
  { kanji:"今", on:["コン"], kun:["いま"], meaning:"maintenant", lecon:2 },
  { kanji:"半", on:["ハン"], kun:[], meaning:"moitié, demi", lecon:2 },
  { kanji:"刀", on:["トウ"], kun:["かたな"], meaning:"sabre, lame", lecon:2 },
  { kanji:"分", on:["フン","ブン"], kun:["わかる"], meaning:"minute, comprendre", lecon:2 },
  { kanji:"上", on:["ジョウ"], kun:["うえ","うわ","あがる"], meaning:"dessus, haut", lecon:2 },
  { kanji:"下", on:["カ"], kun:["した"], meaning:"dessous, bas", lecon:2 },
  { kanji:"中", on:["チュウ"], kun:["なか"], meaning:"milieu, intérieur", lecon:2 },
  { kanji:"外", on:["ガイ"], kun:["そと"], meaning:"extérieur, dehors", lecon:2 },
  { kanji:"川", on:["セン"], kun:["かわ","がわ"], meaning:"rivière", lecon:2 },

  // ──────────── LEÇON 3 ────────────
  { kanji:"右", on:["ウ","ユウ"], kun:["みぎ"], meaning:"droite", lecon:3 },
  { kanji:"工", on:["コウ","ク"], kun:[], meaning:"travail, artisan", lecon:3 },
  { kanji:"左", on:["サ"], kun:["ひだり"], meaning:"gauche", lecon:3 },
  { kanji:"前", on:["ゼン"], kun:["まえ"], meaning:"devant, avant", lecon:3 },
  { kanji:"後", on:["ゴ","コウ"], kun:["あと","うしろ"], meaning:"derrière, après", lecon:3 },
  { kanji:"午", on:["ゴ"], kun:[], meaning:"midi (cheval, heure du cheval)", lecon:3 },
  { kanji:"門", on:["モン"], kun:[], meaning:"portail, porte", lecon:3 },
  { kanji:"間", on:["カン","ゲン"], kun:["あいだ","ま"], meaning:"intervalle, entre", lecon:3 },
  { kanji:"東", on:["トウ"], kun:["ひがし"], meaning:"est", lecon:3 },
  { kanji:"西", on:["サイ","セイ"], kun:["にし"], meaning:"ouest", lecon:3 },
  { kanji:"南", on:["ナン"], kun:["みなみ"], meaning:"sud", lecon:3 },
  { kanji:"北", on:["ホク"], kun:["きた"], meaning:"nord", lecon:3 },
  { kanji:"田", on:["デン"], kun:["た"], meaning:"rizière, champ", lecon:3 },
  { kanji:"力", on:["リョク","リキ"], kun:["ちから"], meaning:"force, pouvoir", lecon:3 },
  { kanji:"男", on:["ダン"], kun:["おとこ"], meaning:"homme", lecon:3 },
  { kanji:"女", on:["ジョ"], kun:["おんな"], meaning:"femme", lecon:3 },
  { kanji:"子", on:["シ"], kun:["こ"], meaning:"enfant", lecon:3 },
  { kanji:"私", on:["シ"], kun:["わたし","わたくし"], meaning:"moi, privé", lecon:3 },
  { kanji:"何", on:[], kun:["なに","なん"], meaning:"quoi, combien", lecon:3 },

  // ──────────── LEÇON 4 ────────────
  { kanji:"学", on:["ガク","ガッ"], kun:[], meaning:"étudier, école", lecon:4 },
  { kanji:"生", on:["セイ","ショウ","ジョウ"], kun:["いきる","うまれる"], meaning:"vie, naître, étudiant", lecon:4 },
  { kanji:"先", on:["セン"], kun:["さき"], meaning:"avant, professeur", lecon:4 },
  { kanji:"父", on:["フ"], kun:["ちち"], meaning:"père", lecon:4 },
  { kanji:"母", on:["ボ"], kun:["はは"], meaning:"mère", lecon:4 },
  { kanji:"去", on:["キョ","コ"], kun:[], meaning:"partir, passé", lecon:4 },
  { kanji:"年", on:["ネン"], kun:["とし"], meaning:"an, année", lecon:4 },
  { kanji:"毎", on:["マイ"], kun:[], meaning:"chaque, tous les", lecon:4 },
  { kanji:"王", on:["オウ"], kun:[], meaning:"roi", lecon:4 },
  { kanji:"国", on:["コク","ゴク"], kun:["くに"], meaning:"pays, nation", lecon:4 },
  { kanji:"見", on:["ケン"], kun:["みる","みえる","みかける","みせる","みつかる"], meaning:"voir, regarder", lecon:4 },
  { kanji:"行", on:["コウ"], kun:["いく","おこなう"], meaning:"aller, ligne", lecon:4 },
  { kanji:"米", on:["ベイ"], kun:["こめ"], meaning:"riz, États-Unis", lecon:4 },
  { kanji:"来", on:["ライ"], kun:["くる","きます","こない"], meaning:"venir, prochain", lecon:4 },
  { kanji:"食", on:["ショク"], kun:["たべる"], meaning:"manger, nourriture", lecon:4 },
  { kanji:"飲", on:["イン"], kun:["のむ"], meaning:"boire", lecon:4 },
  { kanji:"京", on:["キョウ"], kun:[], meaning:"capitale", lecon:4 },
  { kanji:"天", on:["テン"], kun:[], meaning:"ciel, paradis", lecon:4 },
  { kanji:"文", on:["ブン","モン"], kun:[], meaning:"lettre, texte, culture", lecon:4 },

  // ──────────── LEÇON 5 ────────────
  { kanji:"会", on:["カイ"], kun:["あう"], meaning:"rencontrer, réunion", lecon:5 },
  { kanji:"耳", on:[], kun:["みみ"], meaning:"oreille", lecon:5 },
  { kanji:"聞", on:["ブン"], kun:["き"], meaning:"entendre, écouter", lecon:5 },
  { kanji:"言", on:[], kun:["い","こと"], meaning:"dire, parole", lecon:5 },
  { kanji:"話", on:["ワ"], kun:["はな"], meaning:"parler, histoire", lecon:5 },
  { kanji:"立", on:["リツ"], kun:["た"], meaning:"se lever, debout", lecon:5 },
  { kanji:"待", on:[], kun:["ま"], meaning:"attendre", lecon:5 },
  { kanji:"周", on:[], kun:["まわ"], meaning:"tour, alentours", lecon:5 },
  { kanji:"週", on:["シュウ"], kun:[], meaning:"semaine", lecon:5 },
  { kanji:"大", on:["ダイ","タイ"], kun:["おお"], meaning:"grand, gros", lecon:5 },
  { kanji:"小", on:["ショウ"], kun:["ちい","こ"], meaning:"petit", lecon:5 },
  { kanji:"高", on:["コウ"], kun:["たか"], meaning:"haut, cher", lecon:5 },
  { kanji:"安", on:["アン"], kun:["やす"], meaning:"bon marché, sûr", lecon:5 },
  { kanji:"新", on:["シン"], kun:["あたら"], meaning:"nouveau", lecon:5 },
  { kanji:"古", on:["コ"], kun:["ふる"], meaning:"vieux, ancien", lecon:5 },
  { kanji:"元", on:["ゲン","ガン"], kun:["もと"], meaning:"origine, santé", lecon:5 },
  { kanji:"気", on:["キ","ケ"], kun:[], meaning:"esprit, énergie, atmosphère", lecon:5 },
  { kanji:"多", on:["タ"], kun:["おお"], meaning:"beaucoup, nombreux", lecon:5 },
  { kanji:"少", on:["ショウ"], kun:["すか","すい"], meaning:"peu, rare", lecon:5 },

  // ──────────── LEÇON 6 ────────────
  { kanji:"広", on:["コウ"], kun:["ひろ"], meaning:"large, spacieux", lecon:6 },
  { kanji:"早", on:["ソウ"], kun:["はや"], meaning:"tôt, rapide", lecon:6 },
  { kanji:"長", on:["チョウ"], kun:["なが"], meaning:"long, chef", lecon:6 },
  { kanji:"明", on:["メイ"], kun:["あか","あ","あき"], meaning:"clair, lumineux", lecon:6 },
  { kanji:"好", on:["コウ"], kun:["すき","この"], meaning:"aimer, bon", lecon:6 },
  { kanji:"友", on:["ユウ"], kun:["とも"], meaning:"ami", lecon:6 },
  { kanji:"出", on:["シュツ"], kun:["で","だ"], meaning:"sortir, partir", lecon:6 },
  { kanji:"入", on:["ニュウ"], kun:["はい","い"], meaning:"entrer", lecon:6 },
  { kanji:"市", on:["シ"], kun:["いち"], meaning:"ville, marché", lecon:6 },
  { kanji:"町", on:["チョウ"], kun:["まち"], meaning:"quartier, ville", lecon:6 },
  { kanji:"村", on:["ソン"], kun:["むら"], meaning:"village", lecon:6 },
  { kanji:"雨", on:["ウ"], kun:["あめ"], meaning:"pluie", lecon:6 },
  { kanji:"電", on:["デン"], kun:[], meaning:"électricité, foudre", lecon:6 },
  { kanji:"車", on:["シャ"], kun:["くるま"], meaning:"voiture, véhicule", lecon:6 },
  { kanji:"馬", on:["バ"], kun:["うま"], meaning:"cheval", lecon:6 },
  { kanji:"駅", on:["エキ"], kun:[], meaning:"gare", lecon:6 },
  { kanji:"社", on:["シャ"], kun:[], meaning:"société, entreprise, sanctuaire", lecon:6 },
  { kanji:"校", on:["コウ"], kun:[], meaning:"école", lecon:6 },
  { kanji:"店", on:["テン"], kun:["みせ"], meaning:"magasin, boutique", lecon:6 },

  // ──────────── LEÇON 7 ────────────
  { kanji:"銀", on:["ギン"], kun:[], meaning:"argent (métal), banque", lecon:7 },
  { kanji:"病", on:["ビョウ"], kun:["やまい"], meaning:"maladie, hôpital", lecon:7 },
  { kanji:"院", on:["イン"], kun:[], meaning:"établissement, hôpital, temple", lecon:7 },
  { kanji:"休", on:["キュウ"], kun:["やすみ","やすむ"], meaning:"repos, vacances", lecon:7 },
  { kanji:"走", on:["ソウ"], kun:["はしる"], meaning:"courir", lecon:7 },
  { kanji:"起", on:["キ"], kun:["おきる","おこす"], meaning:"se lever, se produire", lecon:7 },
  { kanji:"貝", on:[], kun:["かい"], meaning:"coquillage", lecon:7 },
  { kanji:"買", on:["バイ"], kun:["かう"], meaning:"acheter", lecon:7 },
  { kanji:"売", on:["バイ"], kun:["うる"], meaning:"vendre", lecon:7 },
  { kanji:"読", on:["ドク","トウ"], kun:["よむ"], meaning:"lire", lecon:7 },
  { kanji:"書", on:["ショ"], kun:["かく"], meaning:"écrire, livre", lecon:7 },
  { kanji:"帰", on:["キ"], kun:["かえる"], meaning:"rentrer, retourner", lecon:7 },
  { kanji:"勉", on:["ベン"], kun:[], meaning:"effort, étude", lecon:7 },
  { kanji:"弓", on:["キョウ"], kun:["ゆみ"], meaning:"arc (arme)", lecon:7 },
  { kanji:"虫", on:["チュウ"], kun:["むし"], meaning:"insecte, ver", lecon:7 },
  { kanji:"強", on:["キョウ"], kun:["つよ","つよさ"], meaning:"fort, puissant", lecon:7 },
  { kanji:"持", on:["ジ"], kun:["もつ","もっていく","もち"], meaning:"tenir, posséder", lecon:7 },
  { kanji:"名", on:["メイ","ミョウ"], kun:["な"], meaning:"nom, célébre", lecon:7 },
  { kanji:"語", on:["ゴ"], kun:["かたる"], meaning:"langue, parler, raconter", lecon:7 },
];
